config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'projects#index'
  resources :projects do 
    resources :tasks do
      member do
        patch :complete 
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2,maximum: 15}
  has_many :tasks 
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: true, length: {minimum: 2,maximum: 60}
  # validates :priority, presence: true
  # validates :deadline, presence: true
  enum priority: [:low,:normal,:important,:critical]

  def priority?
    return priority
  end

  def completed?
    if status.nil? or complated_at.blank?
      return false 
    else
      return true
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

before_action :set_project, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, exept: [:index]


def index
    @project = Project.all
end

def show
end

def new
    @project = Project.new
end

def create
    @project = Project.new(project_params)
    if @project.save
        flash[:success] = 'The project was created'
        redirect_to @project
    else
        flash[:error] = 'The project was not created'
        render :new
    end
end

def edit
end

def update
    if @project.update_attributes(project_params)
        flash[:success] = 'The project has been updated'
        redirect_to @project
    else
        flash[:alert] = 'The project has not been updated'
        render :edit
    end
end

def destroy
    @project.tasks.destroy_all
    @project.destroy
    flash[:alert] = 'The project was deleted'
    redirect_to root_path
end

private 
def set_project
    @project = Project.find(params[:id])
end

def project_params
    params.require(:project).permit(:name,:user_id)
end
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_project
    before_action :set_task, except: [:create]
    before_action :authenticate_user!, except: [:index,:show]
    def create 
        @task = @project.tasks.create(task_params)
        if @task.save
            flash[:success] = 'The new task was created'
            redirect_to @project
        else
            flash[:error] = 'The task was not created'
            redirect_to @project
        end
    end
    def show
    end
    
    def update
        if @task.update_attributes(task_params)
            flash[:success] = 'The task was updated'
            redirect_to @project
        else
            flash[:error] = 'The task was not updated'
            render :edit
        end
    end

    def destroy
        @task = @project.tasks.find(params[:id])
        if @task.destroy
            flash[:success] = "Task was deleted"
        else
            flash[:error] = "Task could not be deleted"
        end
        redirect_to @project
    end

    def complete
        if @task.completed? != false
            @task.update_attribute(:complated_at, nil)
            @task.update_attribute(:status, false)
        else
            @task.update_attribute(:complated_at, Time.now)
            @task.update_attribute(:status, true)
        end
        
        redirect_to @project, notice: "Task status was changed!"
    end

    private
    
    def set_project
        @project = Project.find(params[:project_id])
    end

    def set_task
		@task = @project.tasks.find(params[:id])
	end

    def task_params
        params[:task].permit(:name, :status, :deadline, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for(name)
        {
            success: "alert-success",
            error: "alert-danger",
            danger: "alert-danger",
            alert: "alert-warning",
            notice: "alert-info"
        }[name.to_sym] || name
    end
    def allow_project_edit?(project)
        if  current_user.id == project.user_id or current_user.admin?
            return true
        else
            return false
        end
      end

    def creator_email(project)
    return current_user.email
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/70bd3b211b.js" crossorigin="anonymous"></script>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <div id="nav" class="container">
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm ">
    <% if user_signed_in? %>
    <h5 class="my-0 mr-md-auto font-weight-bold navs"><a class="nav-link active" href="<%= projects_path %>">To-Do</a></h5>
        <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark navs"><%= link_to "Main Page",
        projects_path %>  </span>
        <span class="p-2 text-dark navs"><%= link_to "New Project",
        new_project_path %>  </span>
        <span class="p-2 text-dark"><%= link_to "Profile",
        edit_user_registration_path,class: "btn btn-outline-primary buttons"%>  </span>
        <span class="p-2 text-dark"><%= link_to "Log out",
        destroy_user_session_path, method: :delete,class: "btn btn-outline-primary buttons"%>  </span>
    <% else %>
    <h5 class="my-0 mr-md-auto font-weight-bold navs"><a class="nav-link active" href="<%= projects_path %>">To-Do</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark navs"><%= link_to "Main Page",
      projects_path %>  </span>
      <span class="p-2 text-dark navs"><%= link_to "New Project",
      new_project_path %>  </span>
      <span class="p-2 text-dark"><%= link_to "Log In",
      new_user_session_path, class: "btn btn-outline-primary buttons" %>  </span>
      <span class="p-2 text-dark"><%= link_to "Sign up",
      new_user_registration_path, class: "btn btn-outline-primary buttons" %>  </span>
    <% end %>
    </nav>
  </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" ></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" ></script>
    <div class="container-main">
      <% if flash.any? %>
        <%# <div class="card"> %>
        <% flash.each do |name, message| %>
          <div class="alert <%= bootstrap_class_for(name) %> alert-dismissible" role="alert" style="background-color: rgba(250, 250, 250);
        border: 1px solid gray; margin-left: 5%; margin-right: 5%">
            <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>  
        <% end  %>
        <%# </div> %>
      <% end %>
    
      <%= yield %>
    </div>
    
  </body>
<footer>
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://github.com/OlexandrToloshnyak/Task_manager" > Github</a>
  </div>
</footer>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<div class="card" style="height: 5em !important;">
        <%= f.text_field :name, placeholder: "Project Name",style: "font-size: 1.7em;text-align:center; font-weight: bold;" %>
</div>
<div class="d-flex justify-content-center">
        <%= f.submit "Submit", id: "Submit-project",class: "sbm" %>
</div>
<% end %>

app/views/projects/_new_form.html.erb
<% if @project.errors.any? %>
    <div class="alert alert-danger">
        <h5><%= t('common.errors') %></h5>
        <ul>
            <% @project.errors.full_messages.each do |message|%>
                <li style="font-size: 0.5em;"><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<%= form_for(@project) do |f| %>
<table style="margin-left: 20%">
<th>
    <%= f.hidden_field :user_id, :value => current_user.id %>   
</th>
<th>
    <%= f.text_field :name, placeholder: "Project Name",style: "font-size: 0.5em; font-weight: bold; border: 2px solid #7d9c92" %>
    </th>
<th>
&nbsp;
    <%= f.button :submit,class: "button" do %>
      <i class="fas fa-chevron-down"  style="font-size: 0.5em; padding-bottom: 1.5em;"></i>
    <% end %>
</th>
</table>
<% end %>

app/views/projects/_project.html.erb
<% if user_signed_in? %>
    <% if allow_project_edit?(project) %>
        <article class="project">
            <section class="card mb-4 shadow-sm">
            <h2 title="Rename Project"><%= link_to project.name, edit_project_path(project) %></h2>
            <small class="small">
            <%# render project.tasks %>
            <% project.tasks.each do |task| %>
            <% if task.completed? %>
                <% case task.priority?%>
                <% when nil %>
                    <div class="todo_item">
                        <p class="pr-nil" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= task.name %></strike></p>
                    </div>
                <% when "low" %>
                    <div class="todo_item">
                        <p class="pr-low" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= task.name %></strike></p>
                    </div>
                <% when "normal" %>
                    <div class="todo_item">
                        <p class="pr-normal" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= task.name %></strike></p>
                    </div>
                <% when "important" %>
                    <div class="todo_item">
                        <p class="pr-important" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= task.name %></strike></p>
                    </div>
                <% when "critical" %>
                    <div class="todo_item">
                        <p class="pr-critical" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= task.name %></strike></p>
                    </div>
                <% end %>
            <% else %>
                <% case task.priority?%>
                <% when nil %>
                <div class="todo_item">
                        <p class="pr-nil" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= task.name %></p>
                    </div>
                <% when "low" %>
                    <div class="todo_item">
                        <p class="pr-low" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= task.name %></p>
                    </div>
                <% when "normal" %>
                    <div class="todo_item">
                        <p class="pr-normal" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= task.name %></p>
                    </div>
                <% when "important" %>
                    <div class="todo_item">
                        <p class="pr-important" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= task.name %></p>
                    </div>
                <% when "critical" %>
                    <div class="todo_item">
                        <p class="pr-critical" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= task.name %></p>
                    </div>
                <% end %>
            <% end%>
            <% end %>
            </small>
            <hr>
            <small class="small">
                <%= link_to project_path(project) do %>
                <i class="fa fa-edit" title="Edit"></i>
                <% end %>
                |
                <%= link_to project_path(project), method: :delete, data: { confirm: 'Are you shure?'} do %>
                <i class="fa fa-trash" title="Delete Project"></i>
                <% end %>
            </small>
            </section>
        </article>
    <% end %>
<% end %>

app/views/projects/edit.html.erb
<h1 style="text-align: center;">Edit project</h1>
<% if @project.errors.any? %>
    <div class="alert alert-danger">
        <h5><%= t('common.errors') %></h5>
        <ul>
            <% @project.errors.full_messages.each do |message|%>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1 class="h1"> To-Do: <h1>
<%= render @project %>
<%# <hr> %>
</div>
<div class="container-button">
    <%= link_to "New Project", new_project_path,class: "btn btn-lg btn-block btn-primary buttons" %>
<%# link_to "New Project", new_project_path,class: "btn btn-lg btn-block btn-outline-primary" %>
</div>
<%# <h1>Hello</h1> %>

app/views/projects/new.html.erb
<h1 style="text-align: center;">New Project<h1>
<%= render 'new_form' %>

app/views/projects/show.html.erb
<%# < id="notice"><%= notice %>

<p style="font-size: 2em; text-align: center;">
    <strong><%= render "projects/form" %></strong>
</p>
<div id="projects_wrapper">
    <%= render @project.tasks %>
    <hr>
    <div id="form">
        <%= render "tasks/new_form" %>
    </div>
</div>
<div style="text-align: center; font-size: 2em;" class="lk">
<%= link_to root_path do %>
    <i class="fas fa-arrow-left" title="Back"></i>
<% end %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for([@project, @task]) do |f| %>
    <div class="form-inline" style="margin-left: 5%; margin-right: 10%;">
    <div class="form-group mb-2">
    <%= f.text_field :name, placeholder: "New Task" %>
    </div>
    <div class="form-group mb-5">
    <%= f.input :priority, :as => :select, :collection => [nil,"low", "normal", "important", "critical"], selected: "normal" %>
    </div>
    <div class="form-group p-1 mb-5 inp" >
    <%= f.input :deadline, as: :date, html5: true %>
    </div>
    <%= button_tag type: 'submit', class: "button postfix mx-3 mb-4" do %>
      <i class="fas fa-chevron-down" aria-hidden="true"></i>
  <% end %>
  </div>
<% end %>

app/views/tasks/_new_form.html.erb
<%= simple_form_for([@project, @project.tasks.build]) do |f| %>
    <div class="form-inline" style="margin-left: 5%; margin-right: 10%;">
    <div class="form-group mb-2">
    <%= f.text_field :name, placeholder: "New Task" %>
    </div>
    <div class="form-group mb-5">
    <%= f.input :priority, :as => :select, :collection => [nil,"low", "normal", "important", "critical"], selected: "normal" %>
    </div>
    <div class="form-group p-1 mb-5 inp" >
    <%= f.input :deadline, as: :date, html5: true, selected: nil %>
    </div>
    <%= button_tag type: 'submit', class: "button postfix mx-3 mb-4" do %>
      <i class="fas fa-chevron-down" aria-hidden="true"></i>
  <% end %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="row">
    <% if task.completed? %>
        <% case task.priority?%>
        <% when nil %>
            <div class="todo_item">
                <p class="pr-nil" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></strike></p>
            </div>
        <% when "low" %>
            <div class="todo_item">
                <p class="pr-low" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></strike></p>
            </div>
        <% when "normal" %>
            <div class="todo_item">
                <p class="pr-normal" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></strike></p>
            </div>
        <% when "important" %>
            <div class="todo_item">
                <p class="pr-important" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></strike></p>
            </div>
        <% when "critical" %>
            <div class="todo_item">
                <p class="pr-critical" style="opacity: 0.4; margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><strike><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></strike></p>
            </div>
        <% end %>
        <div id ="task-update" class="trash navs">
                <%= link_to edit_project_task_path(@project, task.id) do %>
                <i class="fa fa-edit"> </i>
                <% end %>
        </div>
        |
        <div class="trash navs">
            <%= link_to project_task_path(@project, task.id), method: :delete, data: { confirm: "Are you shure?"} do %>
                <i class="fa fa-trash-o"> </i>
                <% end %>
        </div>
    <% else %>
        <% case task.priority?%>
        <% when nil %>
        <div class="todo_item">
                <p class="pr-nil" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>> <%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
        <% when "low" %>
            <div class="todo_item">
                <p class="pr-low" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
        <% when "normal" %>
            <div class="todo_item">
                <p class="pr-normal" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
        <% when "important" %>
            <div class="todo_item">
                <p class="pr-important" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
        <% when "critical" %>
            <div class="todo_item">
                <p class="pr-critical" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
        <% end %>
            <div id ="task-update" class="trash navs">
                <%= link_to edit_project_task_path(@project, task.id) do %>
                <i class="fa fa-edit"> </i>
                <% end %>
            </div>
            |
            <div class="trash navs">
                <%= link_to project_task_path(@project, task.id), method: :delete, data: { confirm: "Are you shure?"} do %>
                <i class="fa fa-trash-o"> </i>
                <% end %>
            </div>

    <% end%>
</div>

<%# link_to "Edit", some_path %>

app/views/tasks/_task1.html.erb
<div class="row">
     <% case task.priority?%>
        <% when nil %>
        <div class="todo_item">
                <p class="pr-nil" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>> <%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
        <% when "low" %>
            <div class="todo_item">
                <p class="pr-low" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
        <% when "normal" %>
            <div class="todo_item">
                <p class="pr-normal" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
        <% when "important" %>
            <div class="todo_item">
                <p class="pr-important" style="margin-left: 2em;" title=<%= "Deadline:#{task.deadline}" %>><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
        <% when "critical" %>
            <div class="todo_item">
                <p class="pr-critical" style="margin-left: 2em;" title=<%= "#{task.priority}Deadline:#{task.deadline}" %>><%= link_to task.name,  complete_project_task_path(@project, task.id), method: :patch %></p>
            </div>
            <% else %>
            fasfasfasfasfasfasf
        <% end %>
</div>
<%# link_to "Edit", some_path %> 

app/views/tasks/edit.html.erb
<h1 style="text-align: center;">Edit task</h1>

<%= render 'form' %>